### ISSUE TITLE
이벤트 처리 방식 설계 문의

### ISSUE THREAD

**Issue by pro0331** [CNAPS-MSA/CNAPS3#92]
안녕하세요, 
[RentalProducer.java](https://github.com/CNAPS-MSA/CNAPS3/blob/master/contents/jhipster_kafka.md#rentalproducerjava)에서는 각 수신자를 위한 이벤트를 따로 만들어서 보내게 되어 있습니다.
그런데 Rental에서는 대출됨 / 반납됨 이벤트만 생성하고, 도서/사용자/카탈로그 서비스에서 해당 이벤트를 받아서 각자 필요한 처리를 하는 형태를 더 많이 본 것 같고, 이렇게 하는 것이 조금 더 커플링을 낮추는 방법 같아 보이는데요,
혹시 책에서와 같은 형태로 이벤트를 처리하는 것이 다른 장점이 있는지 궁금합니다.

**Comment by cnaps** [comment]
안녕하세요 
답변이 늦었습니다. 죄송합니다.
제가 질문을 정확이 이해 했는지 모르겠네요. 아마도 도메인 모델에서 직접 도메인이벤트를 만들어서 보내지 않은 이유를 물으신 것 같은데요? 맞는지 모르겠습니다. 
우선 예제를 구조와 의도를 설명하면 예제에서는 서비스 구현체가 있는 응용계층에서 비동기 이벤트를 보내기 위해 아웃바운드 포트를 호출하게 되어 있고 이는  도메인에서 바로 카프카로 구현된 어댑터를 호출하면 내부영역에서의 외부영역으로의 의존성이 생긴다 생각해서 입니다. ^ ^ 답변이 되었는지 모르겠네요. 
감사합니다.

**Comment by pro0331** [comment]
@cnaps 안녕하세요, 우선 질문 확인해 주셔서 감사합니다.

제가 여쭤본 내용은 
 - 사건 A 이후에 작업 B와 C를 수행해야 하는 경우에, 
     - A_HAPPENED 이벤트 하나를 발생시키고 다른 서비스에서 그 이벤트를 받아서 처리하는 방식 (발생한 사건에 대한 정보가 이벤트에 포함)
     - A에서 DO_B와 DO_C 이벤트를 각각 발생시켜서 처리하는 방식 (실행할 명령에 대한 정보가 이벤트에 포함)

의 차이에 대한 질문이었습니다. 

책에는 두번째 형태로 구현되어 있어서, 혹시 첫번째 방식에 비해 어떤 장점이 있어서 이 방식을 채택하신 건지가 궁금했습니다.

**Comment by cnaps** [comment]
아 예 재질문해주신 것을 보니 제가 질문을 잘못 이해한 듯 하네요. ^ ^
답변을 드리면 아마도 
        rentalProducer.updateBookStatus(bookId, "AVAILABLE");
        rentalProducer.updateBookCatalogStatus(bookId, "RETURN_BOOK");

이렇게 도메인이벤트 자체를 받아서 판단하는 형태가 아닌 특정 실행명령를 보낸것을 지적하시는 것 같네요.
움 우선 주신 의견중 내부영역의 순수성을 지킨다는 측면에서 첫번째 방식이 바람직 할 것 같습니다.
그런데 당시에 저희가  두번째와 같이 한 까닭은 단순하게도 코드를 좀 더 읽기 쉽게 하기 위해서였습니다.^ ^ 
이벤트 드리븐한 방식을 설명하기 위해 여러 예제를 만들다 보니 계속 코드가 증가하고 글로 설명하기도 힘들것 같아 비동기 통신 방식을 사용한다는 점만 강조하여 직관적으로 이해시키기 위해 그렇게 했는데  지금 보니 부족한 점이 있었네요. 
만약 추가로 재출간이 된다면 보완하도록 하겠습니다. 

관심 정말 감사합니다.

**Comment by pro0331** [comment]
답변 감사합니다!
